### ISSUE TITLE
verifying http/3 shows up correctly

### ISSUE THREAD

**Issue by hpvd** [bsiegel/http-version-indicator#18]
just found the information ff89 beta should have http3 usage enabled by default
https://hacks.mozilla.org/2021/04/quic-and-http-3-support-now-in-firefox-nightly-and-beta/

when visiting some of the test urls named to support http/3 mentioned on this site
https://bagder.github.io/HTTP3-test/

I couldn't get the version indicator showing http/3.

Which test server could one visit?

Or are there other preparation to do, to connect via http/3 beside using latest FF beta?

**Comment by hpvd** [comment]
as mentoined in https://github.com/bsiegel/http-version-indicator/issues/13#issuecomment-827456829

addon works fine on: https://www.google.com/
-> can confirm this!

so it should be a FF thing, that  http/3 is not used on sites mentoined above.

**Comment by Nothing4You** [comment]
works fine for me on second load. first load of https://quic.tech:8443/ loads http2, second load uses http3.
this is on ff88 with `network.http.http3.enabled=true`

**Comment by hpvd** [comment]
yes, on second loads it works on https://quic.tech:8443/  :-)

**Comment by bsiegel** [comment]
This is the correct behavior. If you look in the DevTools Network pane you'll see the same thing - the first visit will load over HTTP/2. This is because support for HTTP/3 usually has to be negotiated - the page is loaded first over an older protocol and includes an "Alt-Svc" header in the response that tells Firefox that it can use HTTP/3 next time.

There is work ongoing to improve this using new "HTTPS" DNS records. Cloudflare has a great write-up about it here: https://blog.cloudflare.com/speeding-up-https-and-http-3-negotiation-with-dns/

**Comment by hpvd** [comment]
@bsiegel Many thanks for explanation and link to cloudflare!
